### ISSUE TITLE
Allow removal and/or change of account/password

### ISSUE THREAD

**Issue by finn-matti** [magnars/mytomatoes.clj#1]
Hello, I know this is an old project, but a friend of mine recently had a data breach and then we noticed that she uses the service and you can't delete your account or change it in any way. Could this still be implemented?

**Comment by magnars** [comment]
Hi! Your friend can change their password by going throught the recovery process, available here: http://mytomatoes.com/recovery 

It's a bit more involved than what you hoped for, perhaps, but it should suffice for your needs.

**Comment by finn-matti** [comment]
Thanks for reacting so quickly.
