### ISSUE TITLE
Fix certificate issue / make site available on HTTPS

### ISSUE THREAD

**Issue by lilymatcha** [magnars/mytomatoes.clj#2]
There seem to be issues with the certificate for the site--the lock next to the domain shows that it's not secure. When I try to connect to the site via HTTPS, it gives ERR_CERT_COMMON_NAME_INVALID. Seems like the issue is that the cert is from another domain owned by the same developer. Is there a way to issue a cert specifically for this app?

**Comment by magnars** [comment]
In celebration of the upcoming one-year anniversary of this issue being made, I have added https to mytomatoes. :)
