### ISSUE TITLE
Which repo is in production ?

### ISSUE THREAD

**Issue by atakanyenel** [magnars/mytomatoes.clj#3]
Hello, I really love this site and use it since 2016. 

I'm currently in the process of writing it with Elm and Python, for learning Elm. I'm doing the frontend by replicating the functionality in the website. 

Does mytomatoes.com use the codebase from this repo or from tararoskell/mytomatoes.com ? That way I can refer to the correct repo for backend.

**Comment by magnars** [comment]
Hi Atakan!

I'm glad to hear you're finding mytomatoes useful. :-) This is the repo currently running in prod. The other one is a fork of the old PHP-version of the site.

Best of luck with your Elm and Python!
